apiVersion: v1
kind: Secret
metadata:
  name: asecret
type: Opaque
data:
  #DUMMY KEY VALUES - NEVER COMMIT REAL VALUES
  JWT_SECRET: ZGVubWFyaw==
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  VITE_AUTH_URL: dawd