
apiVersion: v1
kind: Service
metadata:
  labels:
    run: frontend
  name: service-frontend
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    run: frontend
  type: ClusterIP